# Generated by Django 5.0.4 on 2026-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("acitve", "Active"),
                    ("inactive", "Inactive"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
